language: csharp
dist: trusty
language: csharp
mono: none
dotnet: 3.1.0
solution: InstaSharper.sln

script:
  - cd InstaSharper
  - dotnet --info
  - dotnet restore
  - dotnet build  --framework netstandard2.0
